server:
 port: 8080
spring:
 redis:
  host: 192.168.22.128
  port: 6379
  client-name: data-redis
  database: 0
 datasource:
  url: jdbc:mysql://192.168.22.128:3306/licon
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
 elasticsearch:
  uris: http://192.168.22.128:9200
 jpa:
  hibernate:
   ddl-auto: update
logging:
 level:
  com:
   licon: debug