spring:
  profiles:
    active: com
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: utf-8
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
com:
  licon:
    jwt:
      header: LiconAuth
      prefix: "Bearer "
      access-token-expire-time: 360000
      refresh-token-expire-time: 720000