server:
 port: 8081
spring:
 redis:
  cluster:
   nodes:
     - ${virtual_ip:localhost}:6379
     - ${virtual_ip:localhost}:6380
     - ${virtual_ip:localhost}:6381
     - ${virtual_ip:localhost}:6382
     - ${virtual_ip:localhost}:6383
     - ${virtual_ip:localhost}:6384
 datasource:
  url: jdbc:mysql://${virtual_ip:localhost}:3306/licon
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    auto-commit: false
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    pool-name: hikari
 elasticsearch:
  uris: http://${virtual_ip:localhost}:9200
logging:
  level:
    com:
      licon: debug
    org:
      hibernate: DEBUG
      springframework:
        data: DEBUG
        jdbc: DEBUG
        ldap: DEBUG
        security: DEBUG
    web: DEBUG