server:
 port: 8080
spring:
 redis:
  host: 192.168.22.128
  port: 6379
  client-name: data-redis
  database: 0
 datasource:
  url: jdbc:mysql://192.168.22.128:3306/licon
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    auto-commit: false
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    pool-name: hikari
 elasticsearch:
  uris: http://192.168.22.128:9200
logging:
 level:
  com:
   licon: debug
  org:
    hibernate: DEBUG
    springframework:
      data: DEBUG
      jdbc: DEBUG
      ldap: DEBUG
      security: DEBUG
  web: DEBUG