server:
 port: 8081
spring:
 redis:
  cluster:
   nodes:
     - ${virtual_ip:localhost}:6379
     - ${virtual_ip:localhost}:6380
     - ${virtual_ip:localhost}:6381
     - ${virtual_ip:localhost}:6382
     - ${virtual_ip:localhost}:6383
     - ${virtual_ip:localhost}:6384
 datasource:
  url: jdbc:mysql://${virtual_ip:localhost}:3306/licon
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
 elasticsearch:
  uris: http://${virtual_ip:localhost}:9200
logging:
  level:
    com:
      licon: debug