server:
 port: 8081
spring:
 redis:
  cluster:
   nodes:
     - 172.20.187.3:6379
     - 172.20.187.3:6380
     - 172.20.187.3:6381
     - 172.20.187.3:6382
     - 172.20.187.3:6383
     - 172.20.187.3:6384
 datasource:
  url: jdbc:mysql://172.20.187.3:3306/licon
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
 elasticsearch:
  uris: http://172.20.187.3:9200
logging:
  level:
    com:
      licon: debug